language: cpp
dist: xenial
services:
  - xvfb
compiler: gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install qtdeclarative5-dev qt5-default

addons:
  sonarcloud:
    organization: "fragers"
  apt:
    update: true

script:
  - qmake
  - xvfb-run make test
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.verbose=true -X

cache:
 directories:
 - '$HOME/.sonar/cache'

notifications:
  email: false
